command = '/home/billerot/Git/player-flask/venv/bin/gunicorn'
pythonpath = '/home/billerot/Git/player-flask'
workers = 1
# user = 'billerot'
bind = '127.0.0.1:8053'
logconfig = "/home/billerot/Git/player-flask/logging.conf"
capture_output = True
timeout = 90
reload = True
