command = '/home/billerot/Git/alexa-flask/venv/bin/gunicorn'
pythonpath = '/home/billerot/Git/alexa-flask'
workers = 3
user = 'billerot'
bind = '0.0.0.0:8088'
pid = '/home/billerot/Git/alexa-flask/log/alexa-pid'
errorlog = '/home/billerot/Git/alexa-flask/log/error.log'
accesslog = '/home/billerot/Git/alexa-flask/log/access.log'
access_log_format = '%({X-Real-IP}i)s %({X-Forwarded-For}i)s %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
loglevel = 'warning'
capture_output = True
timeout = 90
